[project]
name = "app"
version = "0.1.0"
description = ""
authors = [
    {name = "Hannan Ali",email = "hannanafc18@gmail.com"},
    {name = "Matthew Potter",email = "matthewpotter154@gmail.com"},
    {name = "Adam Driscoll",email = "adamdriscoll2005@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas (>=3.0.0,<4.0.0)",
    "flask (>=3.1.2,<4.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "numpy (>=2.4.2,<3.0.0)"
    "matplotlib (>=3.10.8,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
