"""Change tmdb_id to movie_id

Revision ID: 005a9b143a34
Revises: 98cef91cd611
Create Date: 2026-03-03 09:00:00.006115

"""
from alembic import op
import sqlalchemy as sa
from app.models import Encrypted, encryption_key


# revision identifiers, used by Alembic.
revision = '005a9b143a34'
down_revision = '98cef91cd611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', Encrypted(encryption_key=encryption_key), nullable=False))
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.TEXT(), nullable=False))
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
