"""Add LikeMovies table.

Revision ID: 14dac5a1e496
Revises: 99ab80336c1e
Create Date: 2026-03-05 12:33:04.925371

"""
from alembic import op
import sqlalchemy as sa
from app.models import Encrypted, encryption_key


# revision identifiers, used by Alembic.
revision = '14dac5a1e496'
down_revision = '99ab80336c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', Encrypted(encryption_key=encryption_key), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liked_movie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liked_movie_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liked_movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liked_movie_user_id'))

    op.drop_table('liked_movie')
    # ### end Alembic commands ###
