"""Add cached recommendations table.

Revision ID: 573529391ef9
Revises: 14dac5a1e496
Create Date: 2026-03-06 15:02:02.384765

"""
from alembic import op
import sqlalchemy as sa
from app.models import Encrypted


# revision identifiers, used by Alembic.
revision = '573529391ef9'
down_revision = '14dac5a1e496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', Encrypted(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], "test_user_id" ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cached_recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_recommendation_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_recommendation_user_id'))

    op.drop_table('cached_recommendation')
    # ### end Alembic commands ###
