"""Encrypt tmdb_id and add rating.

Revision ID: 98cef91cd611
Revises: 50102af3b1c0
Create Date: 2026-03-02 20:05:53.735039

"""
from alembic import op
import sqlalchemy as sa
from app.models import Encrypted


# revision identifiers, used by Alembic.
revision = '98cef91cd611'
down_revision = '50102af3b1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', Encrypted(), nullable=False))
        batch_op.alter_column('tmdb_id',
               existing_type=sa.INTEGER(),
               type_=Encrypted(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_movie_rating_tmdb_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_rating_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.alter_column('tmdb_id',
               existing_type=Encrypted(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
