"""Organise recommendation caches into sets.

Revision ID: cdd576213dcc
Revises: 49c983cdaabd
Create Date: 2026-03-10 09:32:38.889022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd576213dcc'
down_revision = '49c983cdaabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_set_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('cached_recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_set_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_cached_recommendation_user_id'))
        batch_op.create_index(batch_op.f('ix_cached_recommendation_user_set_id'), ['user_set_id'], unique=False)
        batch_op.drop_constraint("test_user_id", type_='foreignkey')
        batch_op.create_foreign_key("test_user_set_id", 'recommendation_set', ['user_set_id'], ['id'])
        batch_op.drop_column('timestamp')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint("test_user_set_id", type_='foreignkey')
        batch_op.create_foreign_key("test_user_id", 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_cached_recommendation_user_set_id'))
        batch_op.create_index(batch_op.f('ix_cached_recommendation_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('user_set_id')

    with op.batch_alter_table('recommendation_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_set_user_id'))

    op.drop_table('recommendation_set')
    # ### end Alembic commands ###
