"""Add movie cache model.

Revision ID: 17dccc5a2d51
Revises: b2a909fb0fba
Create Date: 2026-03-29 21:23:21.280791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dccc5a2d51'
down_revision = 'b2a909fb0fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_movie_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=256), nullable=True),
    sa.Column('backdrop_path', sa.String(length=256), nullable=True),
    sa.Column('release_date', sa.String(length=32), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cached_movie_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_movie_metadata_movie_id'), ['movie_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cached_movie_metadata_tmdb_id'), ['tmdb_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_movie_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_movie_metadata_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_cached_movie_metadata_movie_id'))

    op.drop_table('cached_movie_metadata')
    # ### end Alembic commands ###
