"""Add movie lookup field for MovieRating as well.

Revision ID: 3e89c1527781
Revises: a1f6fbab0198
Create Date: 2026-04-01 20:28:37.655002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e89c1527781'
down_revision = 'a1f6fbab0198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id_lookup', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_movie_rating_movie_id_lookup'), ['movie_id_lookup'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_rating_movie_id_lookup'))
        batch_op.drop_column('movie_id_lookup')

    # ### end Alembic commands ###
