"""Implement per user encryption.

Revision ID: 49c983cdaabd
Revises: 573529391ef9
Create Date: 2026-03-09 14:56:41.252422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c983cdaabd'
down_revision = '573529391ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_dek', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('dek_salt', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dek_salt')
        batch_op.drop_column('encrypted_dek')

    # ### end Alembic commands ###
