"""Fix cascading issues.

Revision ID: 4a8fb46a4b1d
Revises: 6751517d0dd1
Create Date: 2026-03-28 16:55:57.790962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8fb46a4b1d'
down_revision = '6751517d0dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_recommendation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('test_user_set_id'), type_='foreignkey')
        batch_op.create_foreign_key("test_user_set_id", 'recommendation_set', ['user_set_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recommendation_set', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('test_user_id'), type_='foreignkey')
        batch_op.create_foreign_key("test_user_id", 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_set', schema=None) as batch_op:
        batch_op.drop_constraint("test_user_id", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('test_user_id'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('cached_recommendation', schema=None) as batch_op:
        batch_op.drop_constraint("test_user_set_id", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('test_user_set_id'), 'recommendation_set', ['user_set_id'], ['id'])

    # ### end Alembic commands ###
