"""Add TMDB API key field.

Revision ID: 6751517d0dd1
Revises: cdd576213dcc
Create Date: 2026-03-13 14:35:45.597664

"""
from alembic import op
import sqlalchemy as sa
from app.models import Encrypted


# revision identifiers, used by Alembic.
revision = '6751517d0dd1'
down_revision = 'cdd576213dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_api_key', Encrypted(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tmdb_api_key')

    # ### end Alembic commands ###
