"""Add movie id hash to liked movie model.

Revision ID: a1f6fbab0198
Revises: d7bc12a796f9
Create Date: 2026-03-31 21:07:25.632621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f6fbab0198'
down_revision = 'd7bc12a796f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liked_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id_lookup', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_liked_movie_movie_id_lookup'), ['movie_id_lookup'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liked_movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liked_movie_movie_id_lookup'))
        batch_op.drop_column('movie_id_lookup')

    # ### end Alembic commands ###
