"""Add extra field for TMDB API key info.

Revision ID: b2a909fb0fba
Revises: 4a8fb46a4b1d
Create Date: 2026-03-29 18:39:51.329931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a909fb0fba'
down_revision = '4a8fb46a4b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_api_key_valid', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('tmdb_api_key_last_validated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tmdb_api_key_last_validated_at')
        batch_op.drop_column('tmdb_api_key_valid')

    # ### end Alembic commands ###
