"""Add cast details to movie cache model.

Revision ID: d7bc12a796f9
Revises: 17dccc5a2d51
Create Date: 2026-03-31 18:10:41.658560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bc12a796f9'
down_revision = '17dccc5a2d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_movie_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cast', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_movie_metadata', schema=None) as batch_op:
        batch_op.drop_column('cast')

    # ### end Alembic commands ###
