[project]
name = "movie-recommendation-system"
version = "0.1.0"
description = ""
authors = [
    {name = "Hannan Ali",email = "hannanafc18@gmail.com"},
    {name = "Matthew Potter",email = "matthewpotter154@gmail.com"},
    {name = "Adam Driscoll",email = "adamdriscoll2005@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "pandas (>=3.0.0,<4.0.0)",
    "flask (>=3.1.2,<4.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "line-profiler (>=5.0.1,<6.0.0)",
    "progressbar (>=2.5,<3.0)",
    "flask-login (>=0.6.3,<0.7.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "flask-wtf (>=1.2.2,<2.0.0)",
    "flask-migrate (>=4.1.0,<5.0.0)",
    "flask-mail (>=0.10.0,<0.11.0)",
    "pyjwt (>=2.11.0,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "cryptography (>=46.0.5,<47.0.0)",
    "nh3 (>=0.3.3,<0.4.0)",
    "aiosmtpd (>=1.4.6,<2.0.0)",
    "flask-cors>=6.0.2,<7.0.0",
    "flask-jwt-extended (>=4.7.1,<5.0.0)",
    "flask-socketio (>=5.6.1,<6.0.0)",
    "eventlet (>=0.40.4,<0.41.0)",
    "psutil (>=7.2.2,<8.0.0)",
]

[tool.uv]
package = false
